// Every stack-geometry coupling found by the walls plan's four maps (research, terrain, domeetc, rocksetc; ids
// are map#index in walls_plan_all.json), with the anchor keys that record it. anchors.mjs fails the coverage
// check if all keys of a coupling come out empty. `partial` says what a key only stands in for: those parts
// are checked by the lead's frames/bench, not here.
export const COUPLINGS = [
  { id: 'research#0', what: 'M.cliff shared by walls, tor, piles, cave hood', keys: ['sharedMaterials.cliff', 'stacks.dome.materials.cliff', 'stacks.dome.group', 'stacks.rocks.group'], partial: 'the look of the shared material is visual' },
  { id: 'research#1', what: "patchMaterial cache key 'db:n' / onBeforeCompile chain", keys: ['stacks.dome.materials.cliff.key', 'stacks.dome.materials.cliff.fs', 'sharedMaterials.cliff.key', 'sharedMaterials.cliff.fs'] },
  { id: 'research#2', what: 'Textures.rock shared (cliff, stone, flagstone)', keys: ['sharedMaterials.cliff.map', 'sharedMaterials.stone.map', 'stacks.dome.materials.cliff.map', 'stacks.dome.materials.cliff.normalMap'] },
  { id: 'research#3', what: 'ledge built from cliffRadius, 1.6 m into the wall', keys: ['dome.ledge.meshMinusLedge', 'tower.ledge.meshMinusLedge'] },
  { id: 'research#4', what: 'Dome features use negative theta (non-periodic noise)', keys: ['dome.ledge.innerR', 'dome.ladder.meshMin', 'dome.cave.mouth'] },
  { id: 'research#5', what: 'θ=0 radial and uv seam', keys: ['stacks.rocks.cliff.rowStats', 'stacks.rocks.cliff.sha.uv'] },
  { id: 'research#6', what: 'cliff row 0 = cap edge ring; crease normals', keys: ['stacks.dome.cliff.row0IsCapRing', 'stacks.dome.cliff.sha.normal', 'stacks.dome.cap.sha.normal'] },
  { id: 'research#7', what: 'rows at min(ey, top) - depth vs features at top - depth', keys: ['dome.ledge.meshMinusLedge', 'stacks.dome.cliff.rowStats'] },
  { id: 'research#8', what: 'cliff collider = rows with depth <= 45 m', keys: ['stacks.dome.colliders.cliffRows', 'stacks.dome.colliders.pieces'] },
  { id: 'research#9', what: 'waterfall probe reads the built cliff mesh', keys: ['rocks.fall.path', 'stacks.rocks.cliff.columns'] },
  { id: 'research#10', what: 'ladders at cliffRadius, height from heightAt', keys: ['dome.ladder.height', 'tower.ladder.height'] },
  { id: 'research#11', what: 'cliffCalm zones (Dome west half, Tower cave arc)', keys: ['dome.ledge.meshMinusLedge', 'tower.ledge.meshMinusLedge', 'stacks.dome.cliff.rowStats'] },
  { id: 'research#12', what: 'scatter rejection sampling shares Rng; edgeR-derived anchors', keys: ['placements.scatter', 'placements.adds', 'rocks.bridgeA', 'stacks.dome.edgeR'] },
  { id: 'research#13', what: 'cloud billboards keep out of r*1.15', keys: ['stacks.rocks.cfg.r', 'stacks.rocks.cliff.rowStats'], partial: 'devMax per row is the flare; billboard intersection itself is visual' },
  { id: 'research#14', what: 'footsteps: feet.y < top - 2.5 plays rock', keys: ['stacks.dome.relief.belowTopMinus2p5', 'stacks.rocks.relief.belowTopMinus2p5'] },
  { id: 'research#15', what: 'Dome level pad and trail dip shapeFn', keys: ['dome.padFlatness', 'dome.ringSlope15to22', 'dome.cabinOrigin'] },
  { id: 'research#16', what: 'Rocks creek bed running min, waterY, lip', keys: ['rocks.bed', 'rocks.waterY', 'rocks.lip'] },
  { id: 'research#17', what: 'bridge anchor A, End top = rocks.top - 16, Rocks-End gap', keys: ['rocks.bridgeA', 'end.landing', 'end.rocksEndGap', 'stacks.end.cfg.top'] },
  { id: 'research#18', what: 'tor/pile grids, sequoia, movable rocks, flowers, frogs, bench follow heightAt', keys: ['rocks.tor.ground', 'rocks.piles', 'rocks.sequoia', 'rocks.movable', 'placements.adds.rocks.flower', 'rocks.frogs', 'rocks.bench'] },
  { id: 'research#19', what: 'cap rim colour band; trail material shares the cap shader', keys: ['stacks.dome.cap.sha.color', 'placements.trails', 'stacks.dome.materials.cap'] },
  { id: 'research#20', what: 'fog hook FOG_PARS_FRAG injected at <common>', keys: ['stacks.dome.materials.cliff.fs'], partial: 'source hash only; whether it still fogs is visual' },
  { id: 'terrain#0', what: 'waterfall clearance probe: one cliff mesh, segs+1 columns, monotonic rows', keys: ['rocks.fall.path', 'rocks.fall.widths', 'stacks.rocks.cliff.monotonic', 'stacks.rocks.cliff.columns'] },
  { id: 'terrain#1', what: 'fall sheet shadow: cylinder edgeR(theta), top + 1', keys: ['rocks.fall.edgeR', 'stacks.rocks.cfg.top'] },
  { id: 'terrain#2', what: 'spiral ledges vs built mesh (-0.34..+0.47 m today)', keys: ['dome.ledge.meshMinusLedge', 'tower.ledge.meshMinusLedge'] },
  { id: 'terrain#3', what: 'Dome ladder + cave', keys: ['dome.ladder', 'dome.cave'] },
  { id: 'terrain#4', what: 'Tower ladder + cave + ledge', keys: ['tower.ladder', 'tower.cave', 'tower.ledge'] },
  { id: 'terrain#5', what: 'cave hood (M.cliff) embedded in the wall', keys: ['dome.cave.platePos', 'stacks.dome.group', 'stacks.tower.group'] },
  { id: 'terrain#6', what: 'Rocks creek bed and pool', keys: ['rocks.bed', 'rocks.waterY'] },
  { id: 'terrain#7', what: 'Rocks tor/piles/sequoia/movable/flowers/bridge placement', keys: ['rocks.tor', 'rocks.piles', 'rocks.sequoia', 'rocks.movable', 'rocks.bridgeA'] },
  { id: 'terrain#8', what: 'End bridge landing and aperture', keys: ['end.landing', 'end.aperture', 'end.flatness'] },
  { id: 'terrain#9', what: 'footstep surface type', keys: ['stacks.dome.relief', 'stacks.rocks.relief'] },
  { id: 'terrain#10', what: 'scatter edge margins', keys: ['placements.scatter'] },
  { id: 'terrain#11', what: 'cap collider, heightAt BVH, cliff collider rows', keys: ['stacks.dome.colliders', 'stacks.dome.cap.sha.position', 'physics.colliders'] },
  { id: 'terrain#12', what: 'cliff rows placed from the rim, not top', keys: ['stacks.dome.cliff.rowStats', 'dome.ledge.meshMinusLedge'] },
  { id: 'terrain#13', what: 'M.cliff / M.stone shared', keys: ['sharedMaterials.cliff', 'sharedMaterials.stone', 'stacks.rocks.materials.cliff', 'stacks.rocks.group'] },
  { id: 'terrain#14', what: 'cabin reflection probe renders the Dome group', keys: ['stacks.dome.group'], partial: 'mesh inventory only; the probe cost is the bench' },
  { id: 'terrain#15', what: 'cloud collars vs flare at 100-230 m', keys: ['stacks.mountain.cliff.rowStats', 'stacks.rocks.cliff.rowStats'], partial: 'flare per row; collar intersection itself is visual' },
  { id: 'terrain#16', what: 'Mountain placement by normalAt', keys: ['mountain.meadow', 'placements.adds.mountain.meadow'] },
  { id: 'terrain#17', what: 'cliffPoint (unused)', keys: ['stacks.dome.cliffPoint'] },
  { id: 'domeetc#0', what: 'Dome level pad, cabin at top + 0.15', keys: ['dome.padFlatness', 'dome.ringSlope15to22', 'dome.cabinOrigin', 'placements.adds.dome.meadow'] },
  { id: 'domeetc#1', what: 'Dome south-lip clamp at the ladder', keys: ['dome.ladder.lipY', 'dome.ladder.rim'] },
  { id: 'domeetc#2', what: 'Dome ladder wall radius, height, attach windows', keys: ['dome.ladder.wallR', 'dome.ladder.meshMin', 'dome.ladder.height'] },
  { id: 'domeetc#3', what: 'Dome ledge (23 samples)', keys: ['dome.ledge.samples', 'dome.ledge.meshMinusLedge'] },
  { id: 'domeetc#4', what: 'Dome cave and elevator top', keys: ['dome.cave', 'dome.elevatorTop'] },
  { id: 'domeetc#5', what: 'Dome cliffCalm hard mask seam and step', keys: ['stacks.dome.cliff.rowStats'] },
  { id: 'domeetc#6', what: 'Dome trail ribbon draped by heightAt', keys: ['placements.trails'] },
  { id: 'domeetc#7', what: 'Dome vegetation, pebbles, garden', keys: ['placements.adds.dome', 'placements.scatter.dome'] },
  { id: 'domeetc#8', what: 'Dome group on PROBE_LAYER', keys: ['stacks.dome.group'] },
  { id: 'domeetc#9', what: 'Tower lip clamp, apron, pylon base', keys: ['tower.powerTower', 'tower.apronFlatness', 'tower.ladder.lipY'] },
  { id: 'domeetc#10', what: 'Tower cave, ledge, ladder facing the Dome', keys: ['tower.ledge', 'tower.cave', 'tower.ladder'] },
  { id: 'domeetc#11', what: 'Mountain path, plateau, shed, observatory, meadow', keys: ['mountain.trail', 'mountain.observatory', 'mountain.shed', 'mountain.meadow'] },
  { id: 'domeetc#12', what: 'End flatten, aperture, landing, deck clearance', keys: ['end.flatness', 'end.aperture', 'end.landing', 'end.deck.endLip'] },
  { id: 'domeetc#13', what: 'Stack.build mesh contract', keys: ['stacks.rocks.cliff.row0IsCapRing', 'stacks.rocks.cliff.columns', 'stacks.rocks.colliders.cliffRows'] },
  { id: 'domeetc#14', what: 'materials: hood/rockpile M.cliff, trail clone, cache key', keys: ['sharedMaterials.cliff.key', 'stacks.rocks.materials.cliff.key', 'stacks.rocks.materials.cap', 'placements.trails'] },
  { id: 'domeetc#15', what: 'footsteps below top - 2.5', keys: ['stacks.dome.relief.belowTopMinus2p5'] },
  { id: 'domeetc#16', what: 'cloud sea uses STACKS r', keys: ['stacks.dome.cfg.r'] },
  { id: 'domeetc#17', what: 'garden sightlines to Rocks (150°) and Tower (-74°)', keys: ['dome.sightline'], partial: 'cap heights in the wedges; the view itself is a frame' },
  { id: 'domeetc#18', what: 'cfg.top as the height knob', keys: ['stacks.dome.cfg.top', 'stacks.end.cfg.top'] },
  { id: 'domeetc#19', what: 'dead/unaffected items (cliffPoint)', keys: ['stacks.dome.cliffPoint'] },
  { id: 'rocksetc#0', what: 'creek bed running minimum', keys: ['rocks.bed'] },
  { id: 'rocksetc#1', what: 'pool level and waterY-derived fx', keys: ['rocks.waterY', 'emitters'] },
  { id: 'rocksetc#2', what: 'tor on the carved cap', keys: ['rocks.tor.top', 'rocks.tor.ground', 'rocks.tor.splash'] },
  { id: 'rocksetc#3', what: 'rock piles at edgeR - radius - 2.5', keys: ['rocks.piles'] },
  { id: 'rocksetc#4', what: 'sequoia, plate and car floor', keys: ['rocks.sequoia.treeY', 'rocks.sequoia.carRect'] },
  { id: 'rocksetc#5', what: 'bridge anchor A and span', keys: ['rocks.bridgeA', 'end.deck'] },
  { id: 'rocksetc#6', what: 'edge waterfall lip and path', keys: ['rocks.fall', 'rocks.lip'] },
  { id: 'rocksetc#7', what: 'cliff rows reference min(edgeY, top)', keys: ['stacks.rocks.cliff.rowStats'] },
  { id: 'rocksetc#8', what: 'walkability under the lip (top-12 m ny)', keys: ['stacks.rocks.cliff.top12MaxNy'], partial: 'the walk-off itself is routes R6' },
  { id: 'rocksetc#9', what: 'movable rocks', keys: ['rocks.movable'] },
  { id: 'rocksetc#10', what: 'frog spots', keys: ['rocks.frogs'] },
  { id: 'rocksetc#11', what: 'scatter and stepping stones share one Rng', keys: ['placements.adds.rocks', 'rocks.steppingStones'] },
  { id: 'rocksetc#12', what: 'footstep surface on Rocks', keys: ['stacks.rocks.relief'] },
  { id: 'rocksetc#13', what: 'tor colours baked for M.cliff', keys: ['stacks.rocks.group', 'sharedMaterials.cliff', 'stacks.rocks.materials.cliff'] },
  { id: 'rocksetc#14', what: 'ladders, ledge, Tower cave at shallow depth', keys: ['dome.ledge', 'tower.ledge', 'dome.ladder', 'tower.cave'] },
  { id: 'rocksetc#15', what: 'End placed from rocks top and r', keys: ['stacks.end.cfg'] },
  { id: 'rocksetc#16', what: 'dev bench points', keys: ['rocks.bench', 'dome.bench'] },
  { id: 'rocksetc#17', what: 'audio emitters', keys: ['emitters'] },
];
